enum TransactionType { income, expense }

class Transaction {
  // Use '?' for fields that are generated by the database (like the ID)
  final int? id; 
  final String title;
  final double amount;
  final String date;
  final TransactionType type; // Crucial for distinguishing income vs. expense

  Transaction({
    this.id,
    required this.title,
    required this.amount,
    required this.date,
    required this.type,
  });

  // Convert the Transaction object into a Map for database storage
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'amount': amount,
      'date': date,
      // Store the enum as an integer: 0 for expense, 1 for income
      'type': type == TransactionType.income ? 1 : 0, 
    };
  }

  // Create a Transaction object from a Map retrieved from the database
  factory Transaction.fromMap(Map<String, dynamic> map) {
    return Transaction(
      id: map['id'],
      title: map['title'],
      amount: map['amount'] is int ? (map['amount'] as int).toDouble() : map['amount'],
      date: map['date'],
      // Convert the integer back to the TransactionType enum
      type: map['type'] == 1 ? TransactionType.income : TransactionType.expense,
    );
  }
}